version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: 
  - Visual Studio 2017
  - Ubuntu
stack: jdk 11
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk11
init:
  - cmd: git config --global core.autocrlf true
build_script:
  - ./gradlew build -x test
after_build:
  - ps: if($env:APPVEYOR_REPO_TAG -eq 'True') { ./gradlew deploy } else { echo "Not creating deploy artifacts because this is not a tag build" }
artifacts:
  - path: build\libs\MapTool-*.jar
    name: MapTool-Jar
  - path: releases\release-*\MapTool-*.exe
    name: MapTool-Windows
  - path: releases\release-*\MapTool-*.deb
    name: MapTool-Linux
deploy:
  - provider: GitHub
    description: Release build from AppVeyor
    auth_token: $(GITHUB_RELEASE_KEY)
    artifact: MapTool-Jar, MapTool-Windows, MapTool-Linux
    draft: false
    prerelease: true
    force_update: false
    on:
      APPVEYOR_REPO_TAG: true
on_success:
  - ps: Invoke-RestMethod $env:APPVEYOR_DISCORD_WEBHOOK_SCRIPT_URL -o send.ps1
  - ps: ./send.ps1 success $env:DISCORD_URL
on_failure:
  - ps: Invoke-RestMethod $env:APPVEYOR_DISCORD_WEBHOOK_SCRIPT_URL -o send.ps1
  - ps: ./send.ps1 failure $env:DISCORD_URL