version: {branch}
skip_non_tags: true
image: Visual Studio 2017
platform: x64
shallow_clone: true
build:
  verbosity: detailed
build_script:
  - gradlew.bat deploy
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
artifacts:
- path: releases\release-1.4.4.0\bundles\MapTool-1.4.4.0.exe
  name: maptool
deploy:
- provider: GitHub
  auth_token:
    secure: HXIHe/F7K2yGOZ0I56DW5PevrQDe+zjyunjORGKYaUGxFtvPYPcmOdjZT69tzHcS
  artifact: maptool
  draft: true
  force_update: true
