version: '{branch}.{build}'
skip_non_tags: true
image: Visual Studio 2017
platform: x64
shallow_clone: true
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
- ps: set path=c:\Program Files (x86)\WiX Toolset v3.11\bin;%path%
build:
  verbosity: detailed
build_script:
- ps: gradlew.bat deploy
before_test:
- ps: echo my build folder is [$env:appveyor_build_folder]
artifacts:
- path: maptool\releases\release-1.4.4.0\bundles\MapTool-1.4.4.0.exe
  name: maptool
deploy:
- provider: GitHub
  auth_token:
    secure: HXIHe/F7K2yGOZ0I56DW5PevrQDe+zjyunjORGKYaUGxFtvPYPcmOdjZT69tzHcS
  artifact: maptool
  draft: true
  force_update: true
